### ISSUE TITLE
[BUG] Incorrect context merging when context is passed via get[...]Details/Value()

### ISSUE THREAD

**Issue by mmito** [open-feature/php-sdk#135]
### Observed behavior

When a `targetingKey` is [set on an OpenAPIClient](https://github.com/open-feature/php-sdk/blob/712d8e4164fb631da1ff418fbe55ef8982fff53f/src/OpenFeatureClient.php#L86), a subsequent context passed via [any of the get[...]Details/Value functions](https://github.com/open-feature/php-sdk/blob/712d8e4164fb631da1ff418fbe55ef8982fff53f/src/OpenFeatureClient.php#L131) is not being correctly merged and the requested `flagKey` is evaluated with the context set initially.

### Expected Behavior

When a `targetingKey` is passed as `$context` for flag evaluation via [any of the get[...]Details/Value functions](https://github.com/open-feature/php-sdk/blob/712d8e4164fb631da1ff418fbe55ef8982fff53f/src/OpenFeatureClient.php#L131), it should updated a previously set client context. The requested `flagKey` should then be evaluated with the updated context.

### Steps to reproduce

To reproduce, we can consider a simple `targetingKey-test` flag definition in a `flags.json` file.

```
{
  "flags": {
    "targetingKey-test": {
      "state": "ENABLED",
      "variants": {
        "false": false,
        "true": true
      },
      "targeting": {
      "if": [
        {"in": [
          {"var": "targetingKey"},
          ["correct_key"]
          ]
        }, false]
      },
      "defaultVariant": "true"
    }
}
```

We can then build a new OpenAPIClient and pass it a default string context.

```
use GuzzleHttp\Client;
use OpenFeature\OpenFeatureAPI;
use OpenFeature\OpenFeatureClient;
use OpenFeature\Providers\Flagd\FlagdProvider;
use OpenFeature\Providers\Flagd\config\HttpConfig;
use OpenFeature\implementation\flags\MutableEvaluationContext;

$api = OpenFeatureAPI::getInstance();
$client = new Client();
$httpFactory = new HttpFactory();

$provider = new FlagdProvider(
  [
    'hostname' => 'localhost',
    'port' => 8013,
    'protocol' => 'http',
    'secure' => false,
    'httpConfig' => new HttpConfig(
      $client,
      $httpFactory,
      $httpFactory,
    ),
  ],
);

$api->setProvider($provider);
$apiClient = $api->getClient('test-client', '1.0');
$apiClient->setEvaluationContext(new MutableEvaluationContext("default"));

```

We can perform the `targetingKey-test` evaluation by passing a targetingKey directly in the getBooleanDetails() function.

```
$flagKey = "targetingKey-test";
$defaultValue = "true";
$updatedContext = new MutableEvaluationContext($targetingKey);


$details = $apiClient->getBooleanDetails($flagKey, $defaultValue, $updatedContext);
```

We can finally inspect the contents of `$details`.

```
var_dump($details);
```

In the output, we can observe that the `value` field of the EvaluationDetails object is set to bool(true), whilst it should be set to bool(false).

**Comment by mmito** [comment]
A fix can be applied by modifying the [EvaluationContextMerger.php merge function](https://github.com/open-feature/php-sdk/blob/712d8e4164fb631da1ff418fbe55ef8982fff53f/src/implementation/flags/EvaluationContextMerger.php#L49). Currently, the newTargetingKey from an updated Context is calculated as follows:

```
$newTargetingKey = null;
if (!is_null($calculatedTargetingKey) && strlen($calculatedTargetingKey) > 0) {
  $newTargetingKey = $calculatedTargetingKey;
} elseif (!is_null($additionalTargetingKey) && strlen($additionalTargetingKey) > 0) {
  $newTargetingKey = $additionalTargetingKey;
}
```

To compute the $newTargetingKey, it first performs checks on the `$calculatedTargetingKey` from the `$initialContext`. However, the if-else blocks should be reversed, as otherwise valid incoming `$additionalTargetingKeys` are never considered as `$newTargetingKeys`.

```
$newTargetingKey = null;
if (!is_null($additionalTargetingKey) && strlen($additionalTargetingKey) > 0) {
  $newTargetingKey = $additionalTargetingKey;
} elseif (!is_null($calculatedTargetingKey) && strlen($calculatedTargetingKey) > 0) {
  $newTargetingKey = $calculatedTargetingKey;
}
```

**Comment by beeme1mr** [comment]
Hey @tcarrio, could you please take a look when you have a moment?
