### ISSUE TITLE
Update SDK to be compliant with spec v0.5.0

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/php-sdk#2]
Update the SDK to be compliant with the v0.5.0 spec.

### ⚠ BREAKING CHANGES

 * https://github.com/open-feature/spec/pull/142 Error codes must be a constrained set of values (e.g. enum).

### Additional changes

 * https://github.com/open-feature/spec/pull/140 Clarify that `reason` must be a string in the `flag resolution details` and `evaluation details`.
 * https://github.com/open-feature/spec/pull/142 Add optional `error message` to `flag resolution details`.
 
## General

 - [x] Add/update a spec version badge on the readme.

[![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.5.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.5.0)

**Full Changelog**: https://github.com/open-feature/spec/compare/v0.4.0...v0.5.0

**Comment by tcarrio** [comment]
The biggest change I see here is the inclusion of the [Error enums](https://github.com/open-feature/spec/blob/main/specification/types.md#error-code)

**Comment by beeme1mr** [comment]
Yeah, it looks like reason is already a string in the PHP implementation. That was also a breaking change in other SDKs which is why we clarified the requirement in the spec.

**Comment by tcarrio** [comment]
`ErrorCode` is implemented as an "enum" (supporting PHP 7.4 and 8.0 which do not have native Enums)

**Comment by tcarrio** [comment]
As far as I can tell this is complete :+1:
